version: "3.8"

services:
  db:
    image: postgres:12.4
    env_file:
      - ./.env
    restart: always
  web:
    image: zaebumba/yamdb_final
    container_name: yamdb
    build: .
    restart: always
    volumes:
      - static:/code/
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static:/code/
    ports:
      - "8080:80"
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static:
