version: "3.8"

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
  web:
    image: zaebumba/yamdb_final
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.6
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static:/static
      - media:/media
    ports:
      - "8080:80"
    depends_on:
      - web
    restart: always
