version: "3.8"

services:
  db:
    image: postgres:12.4
    env_file:
      - ./.env
    restart: always
  web:
    image: zaebumba/yamdb_final
    container_name: yamdb
    build: .
    restart: always
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.6
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - static:/static
      - media:/media
    ports:
      - "8080:80"
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static:
