version: "3.8"

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
  web:
    image: zaebumba/yamdb_final:latest
    restart: always
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static:/code/static
      - media:/code/media
    ports:
      - "8080:80"
    depends_on:
      - web
    restart: always
