version: "3.3"

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
  web:
    image: zaebumba/yamdb_final:latest
    command: /bin/sh -c "
      python manage.py collectstatic --noinput &&
      python manage.py makemigrations --noinput &&
      python manage.py migrate --noinput &&
      python manage.py loaddata db &&
      gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - static:/home/zaebumba/yamdb_final/static
    restart: always
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.6
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/home/zaebumba/yamdb_final/static
      - media:/home/zaebumba/yamdb_final/media
    ports:
      - "8080:80"
    depends_on:
      - web
    restart: always
